# Пользователи
## Зарегистрироваться

POST http://localhost:4000/users/register HTTP/1.1
Content-Type: application/json

{
  "email": "oleg@mail.ru",
  "avatarPath": "oleg_avatar.png",
  "name": "Oleg Olegov",
  "password": "qwerty123",
  "type":"Pro"
}

###

## Авторизоваться

POST http://localhost:4000/users/login HTTP/1.1
Content-Type: application/json

{
  "email": "oleg@main.ru",
  "password": "qwerty123"
}

###

## Загрузить автар пользователя

POST http://localhost:4000/users/oleg123abcde/avatar HTTP/1.1
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary8Fgp40JzFcc

------WebKitFormBoundary8Fgp40JzFcc
Content-Disposition: form-data; name="avatar"; filename="oleg_avatar.png"
Content-Type: image/png

< /Users/klim/Desktop/oleg_avatar.png
------WebKitFormBoundary8Fgp40JzFcc--

##